Source/RecruitmentManagementSystem.App/Controllers/CourseController.cs
using System;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNet.Identity;
using RecruitmentManagementSystem.App.Infrastructure.ActionResults;
using RecruitmentManagementSystem.Core.Models.Course;
using RecruitmentManagementSystem.Data.Interfaces;
using RecruitmentManagementSystem.Model;

namespace RecruitmentManagementSystem.App.Controllers
{
    [Authorize]
    public class CourseController : BaseController
    {
        private readonly ICourseRepository _courseRepository;

        public CourseController(ICourseRepository courseRepository)
        {
            _courseRepository = courseRepository;
        }

        [HttpGet]
        public ActionResult List()
        {
            var models = _courseRepository.FindAll().ProjectTo<CourseModel>();

            if (Request.IsAjaxRequest())
            {
                return new EnhancedJsonResult(models, JsonRequestBehavior.AllowGet);
            }

            return View(models);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseModel model)
        {
            if (!ModelState.IsValid) return View(model);

            _courseRepository.Insert(new Course
            {
                Title = model.Title,
                Description = model.Description,
                CreatedBy = User.Identity.GetUserId(),
                UpdatedBy = User.Identity.GetUserId(),
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            });

            _courseRepository.Save();

            return RedirectToAction("List");
        }
    }
}

Source/RecruitmentManagementSystem.App/Controllers/QuestionCategoryController.cs
using System.Linq;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using RecruitmentManagementSystem.App.Infrastructure.ActionResults;
using RecruitmentManagementSystem.Data.Interfaces;
using RecruitmentManagementSystem.Core.Interfaces;
using RecruitmentManagementSystem.Core.Models.Question;

namespace RecruitmentManagementSystem.App.Controllers
{
    [Authorize]
    public class QuestionCategoryController : BaseController
    {
        private readonly IQuestionCategoryRepository _questionCategoryRepository;

        private readonly IQuestionCategoryService _questionCategoryService;

        public QuestionCategoryController(IQuestionCategoryRepository questionCategoryRepository,
            IQuestionCategoryService questionCategoryService)
        {
            _questionCategoryRepository = questionCategoryRepository;

            _questionCategoryService = questionCategoryService;
        }

        [HttpGet]
        public ActionResult List()
        {
            var model = _questionCategoryService.GetPagedList();

            if (Request.IsAjaxRequest())
            {
                return new EnhancedJsonResult(model, JsonRequestBehavior.AllowGet);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(QuestionCategoryModel question)
        {
            if (!ModelState.IsValid) return View(question);

            _questionCategoryService.Insert(question);

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            var model =
                _questionCategoryRepository.FindAll()
                    .ProjectTo<QuestionCategoryModel>()
                    .FirstOrDefault(x => x.Id == id);

            if (model == null) return new HttpNotFoundResult();

            if (Request.IsAjaxRequest())
            {
                return new EnhancedJsonResult(model, JsonRequestBehavior.AllowGet);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var model =
                _questionCategoryRepository.FindAll()
                    .ProjectTo<QuestionCategoryModel>()
                    .FirstOrDefault(x => x.Id == id);

            if (model == null) return new HttpNotFoundResult();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(QuestionCategoryModel model)
        {
            if (!ModelState.IsValid) return View(model);

            _questionCategoryService.Update(model);

            return RedirectToAction("List");
        }
    }
}

Source/RecruitmentManagementSystem.App/Controllers/QuestionController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using RecruitmentManagementSystem.App.Infrastructure.ActionResults;
using RecruitmentManagementSystem.Core.Models.Question;
using RecruitmentManagementSystem.Data.Interfaces;
using RecruitmentManagementSystem.Core.Interfaces;

namespace RecruitmentManagementSystem.App.Controllers
{
    [Authorize]
    public class QuestionController : BaseController
    {
        private readonly IQuestionRepository _questionRepository;
        private readonly IQuestionService _questionService;

        public QuestionController(IQuestionRepository questionRepository,
            IQuestionService questionService)
        {
            _questionRepository = questionRepository;
            _questionService = questionService;
        }

        [HttpGet]
        public ActionResult List(string categoryName)
        {
            var model = !string.IsNullOrEmpty(categoryName) ? _questionService.GetPagedList().Where(x => x.Category.Name == categoryName) : _questionService.GetPagedList();

            if (Request.IsAjaxRequest())
            {
                return new EnhancedJsonResult(model, JsonRequestBehavior.AllowGet);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            var viewModel = _questionRepository.FindAll().ProjectTo<QuestionModel>().SingleOrDefault(x => x.Id == id);

            if (Request.IsAjaxRequest())
            {
                return new EnhancedJsonResult(viewModel, JsonRequestBehavior.AllowGet);
            }

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(QuestionModel model)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int) HttpStatusCode.BadRequest;
                return new EnhancedJsonResult(ModelState.Values.SelectMany(v => v.Errors));
            }

            _questionService.Insert(model);

            return Json(null);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var viewModel = _questionRepository.FindAll()
                .ProjectTo<QuestionModel>()
                .SingleOrDefault(x => x.Id == id);

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var question = _questionRepository.Find(x => x.Id == id);
            if (question == null) return new HttpNotFoundResult();

            var viewModel = _questionRepository.FindAll().ProjectTo<QuestionModel>().SingleOrDefault(x => x.Id == id);

            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _questionRepository.Delete(_questionRepository.Find(x => x.Id == id));
            _questionRepository.Save();

            return RedirectToAction("List");
        }
    }
}

Source/RecruitmentManagementSystem.App/Controllers/QuizController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using RecruitmentManagementSystem.App.Infrastructure.ActionResults;
using RecruitmentManagementSystem.Core.Interfaces;
using RecruitmentManagementSystem.Core.Models.Quiz;
using RecruitmentManagementSystem.Data.Interfaces;
using RecruitmentManagementSystem.Model;

namespace RecruitmentManagementSystem.App.Controllers
{
    [Authorize]
    public class QuizController : BaseController
    {
        private readonly IQuizService _quizService;
        private readonly IQuizRepository _quizRepository;

        public QuizController(IQuizRepository quizRepository, IQuizService quizService)
        {
            _quizService = quizService;
            _quizRepository = quizRepository;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(QuizModel model)
        {
            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return new EnhancedJsonResult(ModelState.Values.SelectMany(v => v.Errors));
            }

            var quizId = _quizService.CreateQuiz(model);

            return new EnhancedJsonResult(quizId);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var viewModel = _quizRepository.FindAll().ProjectTo<QuizModel>().SingleOrDefault(x => x.Id == id);
            if (Request.IsAjaxRequest())
            {
                return new EnhancedJsonResult(viewModel, JsonRequestBehavior.AllowGet);
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(QuizModel model)
        {
            var entity = _quizRepository.Find(model.Id);

            if (entity == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                ModelState.AddModelError("", "Question not found.");
                return new EnhancedJsonResult(ModelState.Values.SelectMany(v => v.Errors));
            }

            if (!ModelState.IsValid)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return new EnhancedJsonResult(ModelState.Values.SelectMany(v => v.Errors));
            }

            _quizService.Update(model);

            return Json(null);
        }
    }
}

Source/RecruitmentManagementSystem.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="~/favicon.jpg"/>

    <title>RMS - @ViewBag.Title</title>

    @Styles.Render("~/Content/css")
</head>
<body ng-strict-di>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Recruitment Management System", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_Navigation")
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr/>
        <footer class="pull-right">
            <p>&copy; @DateTime.Now.Year - Brain Station 23 Ltd.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/library")
    @Scripts.Render("~/bundles/application")
    @RenderSection("scripts", false)
</body>
</html>

Source/RecruitmentManagementSystem.App/Views/Shared/_Navigation.cshtml
@using Microsoft.AspNet.Identity

@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>

        <li class="dropdown" uib-dropdown>
            <a class="dropdown-toggle" uib-dropdown-toggle role="button" aria-haspopup="true" aria-expanded="false">
                User
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Registered Users", "List", "Account")</li>
                <li>@Html.ActionLink("Register New User", "Register", "Account")</li>
            </ul>
        </li>

        <li class="dropdown" uib-dropdown>
            <a class="dropdown-toggle" uib-dropdown-toggle role="button" aria-haspopup="true" aria-expanded="false">
                Course
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Course List", "List", "Course")</li>
                <li>@Html.ActionLink("Create New Course", "Create", "Course")</li>
                <li>@Html.ActionLink("Create New Quiz", "Create", "Quiz")</li>
            </ul>
        </li>

        <li class="dropdown" uib-dropdown>
            <a class="dropdown-toggle" uib-dropdown-toggle role="button" aria-haspopup="true" aria-expanded="false">
                Question Bank
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Questions", "List", "Question")</li>
                <li>@Html.ActionLink("Create New Question", "Create", "Question")</li>
                <li>@Html.ActionLink("Categories", "List", "QuestionCategory")</li>
                <li>@Html.ActionLink("Create New Category", "Create", "QuestionCategory")</li>
            </ul>
        </li>
    </ul>

    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new {id = "logoutForm", @class = "navbar-right"}))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">

            <li class="dropdown" uib-dropdown>
                <a class="dropdown-toggle" uib-dropdown-toggle role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.GetUserName() <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Account Details", "Details", "Account", new {userId = User.Identity.GetUserId()}, null)</li>
                    <li>@Html.ActionLink("Manage Security", "Security", "Manage")</li>
                    <li role="separator" class="divider"></li>
                    <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                </ul>
            </li>
        </ul>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Log in", "Login", "Account", null, new {id = "loginLink"})</li>
    </ul>
}